### PR TITLE
Craft 4 support

### LINKED ISSUE #6: Roadmap / future craft 4?
Hello. I am looking to use this in a project. Are you planning on porting this to craft 4? Is it still maintained? Thanks! 👌🏼

### PR DESCRIPTION
**Pull request by boboldehampsink**
Closes #6

### CODE REVIEW

**Comment by pette87** [comment]
Hello,
please pull... I need it for Craft CMS 4

**Comment by pette87** [comment]
Hello,

please pull... I need it for Craft CMS 4

**Comment by boboldehampsink** [comment]
@samuelbirch updated to contain the latest changes

**Comment by samuelbirch** [comment]
@boboldehampsink Thanks we'll get this reviewed and merged this week.

**Pull request merged**
